# Docker Compose Configuration for HIT Student Accommodation Portal


services:
  nextjs:
    image: node:18
    container_name: rez-application
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '3001:3000'
    env_file:
      - .env.local
    restart: always
    command: sh -c "npm install && npm run build && npm start"

  # Cron service for automated payment deadline checks
  payment-checker:
    image: alpine:latest
    container_name: rez-payment-checker
    user: "1000:1000"  # Using a non-root user (adjust UID:GID as needed)
    depends_on:
      nextjs:
        condition: service_healthy
    environment:
      - API_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}/api/check-payment-deadlines
      - PAYMENT_CHECK_TOKEN=${PAYMENT_CHECK_TOKEN:-default-secure-token}
    volumes:
      - payment_logs:/var/log
    restart: always
    command: >
      sh -c "
        apk add --no-cache curl &&
        mkdir -p /etc/crontabs &&
        echo '0 */6 * * * curl -X POST -H \"Authorization: Bearer $${PAYMENT_CHECK_TOKEN}\" -H \"Content-Type: application/json\" $${API_URL} >> /var/log/payment-check.log 2>&1' > /etc/crontabs/root &&
        chmod 0600 /etc/crontabs/root &&
        echo 'Payment checker cron job scheduled to run every 6 hours' &&
        crond -f -l 2
      "

networks:
  default:
    name: rez-network

volumes:
  node_modules:
  payment_logs: