import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from "@/components/auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastContainer />
          <main className="w-full h-screen">
            <div className="h-[98%] w-[99%] bg-white rounded-2xl border border-gray-200 shadow-lg mt-2">
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
